insert into Author VALUES (1,'Humayun Ahmed',63,'male');
insert into Author VALUES (2,'John Green',55,'male');	
insert into Author VALUES (3,'Edgar Holmes',52,'male');
insert into Author VALUES (4,'Nita Prose',50,'female');
insert into Author VALUES (5,'Haruki Murakami',73,'male');
insert into Author VALUES (6,'Humayun Ahmed',63,'male');
insert into Author VALUES (7,'Mary Shelley',53,'female');
insert into Author VALUES (8,'Kazuo Ishiguro',67,'male');
insert into Author VALUES (9,'Haruki Murakami',73,'male');
insert into Author VALUES (10,'Seth Rogen',40,'male');
insert into Author VALUES (11,'Humayun Ahmed',63,'male');
insert into Author VALUES (12,'John Green',55,'male');
insert into Author VALUES (13,'John Green',55,'male');
insert into Author VALUES (14,'colleen hoover',40,'female');
insert into Author VALUES (15,'Bibhutibhushan Bandyopadhyay',56,'male');
insert into Author VALUES (16,'Humayun Ahmed',63,'male');
insert into Author VALUES (17,'Khaled Hosseini',40,'male');
insert into Author VALUES (18,'Rabindranath Tagore',40,'male');
insert into Author VALUES (19,'Satyajit Ray',70,'male');
insert into Author VALUES (20,'colleen hoover',40,'female');

insert into Book VALUES (1,'Nondito Noroke',1);										
insert into Book VALUES (2,'Paper Towns',2);										
insert into BooK VALUES (3,'Her Favorite Color Was Yellow',3);						
insert into BooK VALUES (4,'The Maid',4);								         
insert into BooK VALUES (5,'Kafka On The Shore',5);					               
insert into BOOK VALUES (6,'Srabon Megher Din',6);					
insert into BOOK VALUES (7,'Frankenstein',7);							
insert into BOOK VALUES (8,'Klara And The Sun',8);                  
insert into BOOK VALUES (9,'Norwegian Wood',9); 					
insert into BOOK VALUES (10,'Yearbook',10); 								
/*
insert into BOOK VALUES (11,'Jochona O Jononir Golpo',11); 		
insert into BOOK VALUES (12,'Turtles All The Way Down',12);			
insert into BOOK VALUES (13,'Looking For Alaska',13); 				
insert into BOOK VALUES (14,'Hopeless',14); 							
insert into BOOK VALUES (15,'Chander Pahar',15); 		
insert into BOOK VALUES (16,'Debi',16); 								
insert into BOOK VALUES (17,'Sea Prayer',17); 						
insert into BOOK VALUES (18,'Chokher Bali',18);					
insert into BOOK VALUES (19,'Baksho Rahashya',19);					
insert into BOOK VALUES (20,'It Ends With Us',20);					
*/			


insert into BookInfo VALUES (1,1,'novel',4,150);
insert into BookInfo VALUES (2,2,'fiction',4.5,170);
insert into BookInfo VALUES (3,3,'poetry',4,250);
insert into BookInfo VALUES (4,4,'mystry',4.2,350);
insert into BookInfo VALUES (5,5,'fiction',4.1,190);
insert into BookInfo VALUES (6,6,'romance',4.3,220);
insert into BookInfo VALUES (7,7,'fiction',4.4,300);
insert into BookInfo VALUES (8,8,'fiction',4.5,350);
insert into BookInfo VALUES (9,9,'fiction',3.9,345);
insert into BookInfo VALUES (10,10,'comedy',4,270);
insert into BookInfo VALUES (11,11,'fiction',3.8,450);
insert into BookInfo VALUES (12,12,'fiction',3.7,250);
insert into BookInfo VALUES (13,13,'fiction',4.1,380);
insert into BookInfo VALUES (14,14,'fiction',4.2,260);
insert into BookInfo VALUES (15,15,'Adventure',4.7,250);
insert into BookInfo VALUES (16,16,'mystry',4.6,290);
insert into BookInfo VALUES (17,17,'fiction',4.1,400);
insert into BookInfo VALUES (18,18,'drama',4.2,350);
insert into BookInfo VALUES (19,19,'novel',4.7,450);
insert into BookInfo VALUES (20,20,'fiction',4.2,250);

insert into BuyerInfo VALUES (1,'Farzana',23,1000);
insert into BuyerInfo VALUES (2,'Adiba',24,1001);
insert into BuyerInfo VALUES (3,'Fairuz',20,1002);
insert into BuyerInfo VALUES (4,'Rahima',15,1003);
insert into BuyerInfo VALUES (5,'Azhar',30,1004);
insert into BuyerInfo VALUES (6,'Mir',25,1005);
insert into BuyerInfo VALUES (7,'Ibrahim',28,1006);
insert into BuyerInfo VALUES (8,'Insu',31,1007);
insert into BuyerInfo VALUES (9,'Mahnaz',23,1008);
insert into BuyerInfo VALUES (10,'Ira',25,1009);
insert into BuyerInfo VALUES (11,'Oyshi',24,1010);
insert into BuyerInfo VALUES (12,'Washim',33,1011);
insert into BuyerInfo VALUES (13,'akbar',31,1012);
insert into BuyerInfo VALUES (14,'Fatima',23,1013);
insert into BuyerInfo VALUES (15,'Harun',17,1014);
insert into BuyerInfo VALUES (16,'Afia',18,1015);
insert into BuyerInfo VALUES (17,'Samia',23,1016);
insert into BuyerInfo VALUES (18,'Zara',14,1017);
insert into BuyerInfo VALUES (19,'Mahrez',13,1018);
insert into BuyerInfo VALUES (20,'Rim',19,1019);

insert into Buy VALUES (1,1);
insert into Buy VALUES (1,7);
insert into Buy VALUES (2,3);
insert into Buy VALUES (2,8);
insert into Buy VALUES (2,2);
insert into Buy VALUES (3,1);
insert into Buy VALUES (3,11);
insert into Buy VALUES (3,15);
insert into Buy VALUES (3,19);
insert into Buy VALUES (4,20);
insert into Buy VALUES (4,13);
insert into Buy VALUES (4,16);
insert into Buy VALUES (4,17);
insert into Buy VALUES (5,4);
insert into Buy VALUES (5,6);
insert into Buy VALUES (5,9);
insert into Buy VALUES (6,10);
insert into Buy VALUES (6,8);
insert into Buy VALUES (6,18);
insert into Buy VALUES (6,5);
insert into Buy VALUES (7,12);
insert into Buy VALUES (7,19);
insert into Buy VALUES (8,1);
insert into Buy VALUES (8,14);
insert into Buy VALUES (9,20);
insert into Buy VALUES (10,1);
insert into Buy VALUES (11,14);
insert into Buy VALUES (11,15);
insert into Buy VALUES (12,7);
insert into Buy VALUES (13,9);
insert into Buy VALUES (14,13);
insert into Buy VALUES (14,19);
insert into Buy VALUES (15,4);
insert into Buy VALUES (16,8);
insert into Buy VALUES (17,5);
insert into Buy VALUES (18,10);
insert into Buy VALUES (19,17);
insert into Buy VALUES (20,16);
insert into Buy VALUES (20,11);


commit;